# Generated by Django 4.2.2 on 2023-06-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('auth', models.CharField(choices=[('apiKey', 'apiKey'), ('OAuth', 'OAuth'), ('', 'None')], max_length=100)),
                ('cors', models.BooleanField()),
                ('description', models.TextField()),
                ('https', models.BooleanField()),
                ('url', models.URLField()),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='', max_length=100)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.category')),
            ],
        ),
    ]
