# Generated by Django 4.2.1 on 2023-05-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_like_unique_together_remove_like_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
