# Generated by Django 4.2.2 on 2023-06-24 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vault', '0002_remove_api_source_api_owner_apipending'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

