# Generated by Django 4.2.1 on 2023-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_api_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
