# Generated by Django 4.2.2 on 2023-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
