# Generated by Django 4.2.1 on 2023-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultuser',
            name='type',
            field=models.CharField(choices=[('D', 'DEVELOPER'), ('A', 'ADMIN')], default='D', max_length=2),
        ),
    ]
